### ISSUE TITLE
关于17章automatic table layout中pass的翻译

### ISSUE THREAD

**Issue by everywill** [ayqy/CSS2-1#10]
其中的这句In this algorithm (which generally requires no more than two passes)， 这里pass是不是取意 '遍历x遍‘比较好？

**Comment by ayqy** [comment]
好像是这样哈，这里翻译得很难受，仔细考虑下。

**Comment by ayqy** [comment]
已修正，请帮助review。相关变更：

>  In this algorithm (which generally requires no more than two passes), the table's width is given by the width of its columns (and intervening borders). This algorithm reflects the behavior of several popular HTML user agents at the writing of this specification. UAs are not required to implement this algorithm to determine the table layout in the case that 'table-layout' is 'auto'; they can use any other algorithm even if it results in different behavior.

该算法中（一般要求最多遍历两趟（two passes）），表格的宽度由它所包含的列（和中间边框）的宽度决定。该算法反映了编写本规范时几种流行的HTML用户代理的行为。'table-layout'为'auto'时，不要求UA实现该算法来决定表格布局。它们可以用任何其它算法，即使会导致不同的行为

>  This algorithm may be inefficient since it requires the user agent to have access to all the content in the table before determining the final layout and may demand more than one pass.

该算法可能很低效，因为它需要用户代理在确定最终布局之前，拿到表格中所有内容，并且可能需要多趟遍历（more than one pass）
