### ISSUE TITLE
是否考虑切换到 CSS 2.2？

### ISSUE THREAD

**Issue by Justineo** [ayqy/CSS2-1#3]
https://www.w3.org/TR/CSS22/about.html

**Comment by ayqy** [comment]
暂时不考虑，CSS 2.2目前才刚发布了第一个WD，还要经过多次修改才会定稿（Recommendation），见：

> 在本文档的翻译过程中（2016.3.29-2016.5.23），CSS 2.2规范有了新的进展（2016.4.12发布了第一份工作草案）。
> 目前（2016）得到最广泛支持的版本仍然是CSS 2.1（即本规范），关于CSS规范的最新情况查看CSS。
