### ISSUE TITLE
Errata-4.2

### ISSUE THREAD

**Issue by vboar** [ayqy/CSS2-1#4]
4.2中粗体Illegal values翻译成非法值。笔误了嘛:)

**Comment by ayqy** [comment]
其实另一个选择是“无效值”，翻译时权衡过，觉得“非法值”更合适一些

合法值表示能通过词法分析器检测的值，这毫无疑问。对于不满足产生式无法通过词法检测的值，应该与合法值相反，所以整个文档中的`illegal value`都译为“非法值”。

至于“无效值”，“无效”可以表示出现了等于没出现，不影响其它语句规则的东西，含义不如“非法值”单纯，虽然读起来更顺畅些，但为了避免歧义，选择了生涩一点的“非法值”

个人觉得“非法值”更好些，只表示CSS解析器不期望看到的值。当然，翻译这种事情，欢迎讨论

**Comment by vboar** [comment]
额。。。其实我指的是把Illegal values翻译成非法示例额= =

**Comment by ayqy** [comment]
笔误笔误，好像是某次跨文件替换的锅（已经全局查找确认过了）

已更正。感谢勘误，莫省字，说清楚撒:)

**Comment by vboar** [comment]
好的:)
