### ISSUE TITLE
官网上的文档下载链接都 404 了。

### ISSUE THREAD

**Issue by zhouweicsu** [ayqy/CSS2-1#5]
官网上的文档下载链接都 404 了。

**Comment by ayqy** [comment]
> 本文档还有其它非标准格式：plain text, gzip'ed tar file, zip file, gzip'ed PostScript, PDF。

已把下载链接修改为绝对URL。这些文件内容没有经过翻译，目前只是直接指向了英文原文档附件（避免404）

除上述非标准格式文档外，`longdesc`也未翻译（图片脚注的长描述信息，如`[D]`），因为没有必要翻译

感谢反馈
