### ISSUE TITLE
第十章 可视化格式模型详细描述 中讲containing block中的例子有误？

### ISSUE THREAD

**Issue by everywill** [ayqy/CSS2-1#8]
[http://www.ayqy.net/doc/css2-1/visudet.html#containing-block-details](url)

而在em经过绝对定位后，strong的containing block变为em。

但strong为static定位，containing block的确定和em的定位类型应该不相关才是，因此想这是不是例子中出现了错误，请大大指教。

**Comment by ayqy** [comment]
第2条规则有说明：

>  对于其它元素，如果该元素的position是'relative'或者'static'，包含块由其最近的块容器祖先盒的content边形成

文档树里的所有元素都有各自的包含块，初始情况下，大家都是`static`，对应的包含块确定无疑，对`#em1`绝对定位后，**受影响的是其后代元素的包含块**（因为包含块通过向上找来确定）。所以在应用该样式后，`#strong1`的包含块已经变了

包含块是一直存在的，与元素自身定位无关，元素包含块发生变化，肯定是祖先`position`改变引起的

**Comment by everywill** [comment]
感谢大大的回复，之后看下去已经弄明白了，position: absolute将使display为block从而使#em1成为了#strong1的包含块。
